[package]
authors    =['Substrate DevHub <https://github.com/substrate-developer-hub>']
description='FRAME pallet template for defining custom runtime logic.'
edition    ='2021'
homepage   ='https://substrate.dev'
license    ='AGPL-3.0-or-later'
name       ='pallet-constraints'
publish    =false
readme     ='README.md'
repository ='https://github.com/substrate-developer-hub/substrate-node-template/'
version    ='3.0.0-monthly-2021-10'

[package.metadata.docs.rs]
targets=['x86_64-unknown-linux-gnu']

[dev-dependencies.sp-core]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.31"
version         ='6.0.0'

[dependencies.codec]
default-features=false
features        =['derive']
package         ='parity-scale-codec'
version         ='3.0.0'

[dependencies.frame-benchmarking]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.31"
optional        =true
version         ='4.0.0-dev'

[dependencies.frame-support]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.31"
version         ='4.0.0-dev'

[dependencies.frame-system]
default-features=false
git             ='https://github.com/paritytech/substrate.git'
branch          ="polkadot-v0.9.31"
version         ='4.0.0-dev'

[dependencies]

scale-info    ={ version="2.0.1", default-features=false, features=["derive"] }
log           ={ version="0.4.0", default-features=false }
sp-staking    ={ version="4.0.0-dev", default-features=false, git='https://github.com/paritytech/substrate.git', branch="polkadot-v0.9.31" }
sp-io         ={ version="6.0.0", default-features=false, git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.31" }
sp-runtime    ={ version="6.0.0", default-features=false, git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.31" }
sp-std        ={ package="sp-std", git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.31", default-features=false }
entropy-shared={ path="../../crypto/shared", default-features=false }
# pallet-relayer  ={ path="../../pallets/relayer", default-features=false }

[features]
default=['std']
runtime-benchmarks=['frame-benchmarking']
std=[
  'codec/std',
  'log/std',
  "scale-info/std",
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  "sp-io/std",
  "sp-runtime/std",
  # "pallet-relayer/std",
]
try-runtime=['frame-support/try-runtime']
