[package]
name = "client-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
entropy-grpc = { path = "../grpc" }
lazy_static = "1.4.0"
tonic = "0.7.2"
prost = "0.10.3"
tokio = { version = "1.15.0", features = ["rt-multi-thread"] }
tokio-stream = "0.1.8"
log = "0.4.14"
env_logger = "0.9.0"
dotenv = "0.15.0"
